version: "3.9"

services:
  oracle-db:
    image: oracledb:latest
    container_name: oracledb
    environment:
      ORACLE_PWD: SYSTEM
      ORACLE_PDB: XEPDB1
    volumes:
      # - ora-data:/opt/oracle/oradata # persistent oracle database data.
      - ./docker/setup:/opt/oracle/scripts/setup # to be run after database setup, here are all sql and shell scripts needed for DB setup
    ports:
      - 1521:1521
volumes:
  ora-data:
