version: "3.9"

services:
  oracle-db:
    image: oracledb:latest
    container_name: oracledb
    environment:
      ORACLE_PWD: SYSTEM
      ORACLE_PDB: XEPDB1
    volumes:
      - ./docker/setup:/opt/oracle/scripts/setup
    ports:
      - 1521:1521
volumes:
  ora-data:
